openapi: 3.0.3
info:
  title: JSONPlaceholder API Proxy
  version: "1.0.0"
paths:
  /posts/{post_id}:
    get:
      summary: Get a post by ID
      operationId: api.handler.get_post
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A post from JSONPlaceholder
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  body:
                    type: string